---
version: "~> 1.0"

os: linux

language: python

python:
  - '3.8'
  - '3.7'
  - '3.6'

services: docker

cache:
  pip: true
  directories:
  - ".tox"

install:
  - pip install tox-travis
env:
  jobs:
    - TOX_DISTRO=archlinuxlatest   TOX_ANSIBLE=latest
    - TOX_DISTRO=alpinelatest      TOX_ANSIBLE=latest
    - TOX_DISTRO=alpine310         TOX_ANSIBLE=latest
    - TOX_DISTRO=alpine39          TOX_ANSIBLE=latest
    - TOX_DISTRO=centoslatest      TOX_ANSIBLE=latest
    - TOX_DISTRO=centos8           TOX_ANSIBLE=latest
    - TOX_DISTRO=centos7           TOX_ANSIBLE=latest
    - TOX_DISTRO=clearlinuxlatest  TOX_ANSIBLE=latest
    - TOX_DISTRO=debianlatest      TOX_ANSIBLE=latest
    - TOX_DISTRO=debianstable      TOX_ANSIBLE=latest
    - TOX_DISTRO=debian10          TOX_ANSIBLE=latest
    - TOX_DISTRO=debian9           TOX_ANSIBLE=latest
    - TOX_DISTRO=debian8           TOX_ANSIBLE=latest
    - TOX_DISTRO=fedoralatest      TOX_ANSIBLE=latest
    - TOX_DISTRO=fedora31          TOX_ANSIBLE=latest
    - TOX_DISTRO=fedora30          TOX_ANSIBLE=latest
    - TOX_DISTRO=fedora29          TOX_ANSIBLE=latest
    - TOX_DISTRO=fedora28          TOX_ANSIBLE=latest
    - TOX_DISTRO=opensuselatest    TOX_ANSIBLE=latest
    - TOX_DISTRO=opensuse15        TOX_ANSIBLE=latest
    - TOX_DISTRO=ubuntulatest      TOX_ANSIBLE=latest
    - TOX_DISTRO=ubuntu2004        TOX_ANSIBLE=latest
    - TOX_DISTRO=ubuntu1904        TOX_ANSIBLE=latest
    - TOX_DISTRO=ubuntu1804        TOX_ANSIBLE=latest
    - TOX_DISTRO=ubuntu1604        TOX_ANSIBLE=latest
    - TOX_DISTRO=alpinelatest      TOX_ANSIBLE={29,28}
    - TOX_DISTRO=alpine310         TOX_ANSIBLE={29,28}
    - TOX_DISTRO=alpine39          TOX_ANSIBLE={29,28}
    - TOX_DISTRO=centoslatest      TOX_ANSIBLE={29,28}
    - TOX_DISTRO=centos8           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=centos7           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=clearlinuxlatest  TOX_ANSIBLE={29,28}
    - TOX_DISTRO=debianlatest      TOX_ANSIBLE={29,28}
    - TOX_DISTRO=debianstable      TOX_ANSIBLE={29,28}
    - TOX_DISTRO=debian10          TOX_ANSIBLE={29,28}
    - TOX_DISTRO=debian9           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=debian8           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=fedoralatest      TOX_ANSIBLE={29,28}
    - TOX_DISTRO=fedora31          TOX_ANSIBLE={29,28}
    - TOX_DISTRO=fedora30          TOX_ANSIBLE={29,28}
    - TOX_DISTRO=fedora29          TOX_ANSIBLE={29,28}
    - TOX_DISTRO=fedora28          TOX_ANSIBLE={29,28}
    - TOX_DISTRO=opensuselatest    TOX_ANSIBLE={29,28}
    - TOX_DISTRO=opensuse15        TOX_ANSIBLE={29,28}
    - TOX_DISTRO=ubuntulatest      TOX_ANSIBLE={29,28}
    - TOX_DISTRO=ubuntu2004        TOX_ANSIBLE={29,28}
    - TOX_DISTRO=ubuntu1904        TOX_ANSIBLE={29,28}
    - TOX_DISTRO=ubuntu1804        TOX_ANSIBLE={29,28}
    - TOX_DISTRO=ubuntu1604        TOX_ANSIBLE={29,28}
script:
  - tox -e $(echo py${TRAVIS_PYTHON_VERSION} | tr -d .)-ansible${TOX_ANSIBLE}-${TOX_DISTRO}
  - |
    rm -r .tox/py*/log/*
    find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

